---
  
- name: instalando somente no debian
  hosts: all
  tasks:
   - name: instalando pacotes
     command: test -f /etc/profile.d/dexter
     register: result
  
   - name: configurando uma variavel
     shell: echo "export DEXTER=/opt/dexter > /etc/profile.d/dexter"
     when: result.rc == 0
